sonar.organization=sadeeshadman
sonar.projectKey=sadeeshadman_Constein

sonar.sources=apps/frontend/src,apps/backend/src
sonar.tests=apps/frontend/src,apps/backend/src
sonar.test.inclusions=apps/frontend/src/**/*.test.ts,apps/frontend/src/**/*.test.tsx,apps/backend/src/**/*.test.ts
sonar.cpd.exclusions=apps/frontend/src/components/tests/**/*.test.ts,apps/frontend/src/components/tests/**/*.test.tsx,apps/frontend/src/lib/services.ts

sonar.javascript.lcov.reportPaths=apps/frontend/coverage/lcov.info
